# Generated by Django 4.1.4 on 2022-12-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=True, upload_to='category/'),
            preserve_default=False,
        ),
    ]
