# Generated by Django 4.1.5 on 2023-01-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='rating',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
