# Generated by Django 4.1.5 on 2023-01-21 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0008_remove_feedback_rating_delete_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Myapp.rating'),
            preserve_default=False,
        ),
    ]
