# Generated by Django 4.0 on 2023-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0016_payment_address_payment_phone_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/images/succ.jgp', null=True, upload_to='proof/'),
        ),
    ]
