# Generated by Django 4.0 on 2023-05-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0017_payment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, default='/static/assets/images/succ.jpg', null=True, upload_to='proof/'),
        ),
    ]
