# Generated by Django 4.0 on 2023-05-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_alter_payment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='image',
            field=models.ImageField(blank=True, default='/proof/succ.jpg', null=True, upload_to='proof/'),
        ),
    ]
