# Generated by Django 4.0 on 2023-05-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0023_alter_payment_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
