# Generated by Django 4.0 on 2023-05-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0025_alter_order_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, default='/proof/succ.jpg', upload_to='proof/'),
        ),
    ]
